# Generated by Django 4.2.19 on 2025-03-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date', 'time']},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('table', 'date', 'time')},
        ),
    ]
