# Generated by Django 4.2.20 on 2025-03-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('has_children', models.BooleanField(default=False)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('disability_adjustments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
